import type { MissileDefinition, MissileLaunchSite, MissileCountry } from '@/features/missiles/types'

type MissileInput = Omit<
  MissileDefinition,
  | 'altNames'
  | 'guidance'
  | 'launchPlatform'
  | 'warheadType'
  | 'features'
  | 'estimatedInventory'
  | 'interceptProbability'
  | 'defaultLaunchCoord'
  | 'knownLaunchSites'
> & {
  altNames?: string[]
  guidance?: string[]
  launchPlatform?: string[]
  warheadType?: string[]
  features?: string[]
  estimatedInventory?: number | null
  interceptProbability?: number | null
  defaultLaunchCoord?: [number, number]
  knownLaunchSites?: MissileLaunchSite[]
}

export const IRAN_DEFAULT_LAUNCH_COORD: [number, number] = [51.67, 32.65]
export const ISRAEL_DEFAULT_LAUNCH_COORD: [number, number] = [34.9194, 31.7386]

export const IRAN_LAUNCH_SITES: MissileLaunchSite[] = [
  { name: 'Isfahan', coord: [51.67, 32.65], type: 'fixed' },
  { name: 'Khorramabad', coord: [48.2875, 33.4913], type: 'underground' },
  { name: 'Kermanshah', coord: [47.2222, 34.3958], type: 'underground' },
  { name: 'Qom / Fordow', coord: [50.9981, 34.8845], type: 'underground' },
]

export const ISRAEL_LAUNCH_SITES: MissileLaunchSite[] = [
  { name: 'Sdot Micha', coord: [34.9194, 31.7386], type: 'fixed' },
  { name: 'Palmachim', coord: [34.6905, 31.8977], type: 'fixed' },
  { name: 'Nevatim', coord: [35.0116, 31.2083], type: 'fixed' },
]

export const MISSILE_PRESET_TARGETS = [
  { id: 'tel_aviv', label: 'Tel Aviv', coord: [34.7818, 32.0853] as [number, number] },
  { id: 'tehran', label: 'Tahran', coord: [51.389, 35.6892] as [number, number] },
  { id: 'isfahan', label: 'Isfahan', coord: [51.677, 32.6546] as [number, number] },
  { id: 'ankara', label: 'Ankara', coord: [32.8597, 39.9334] as [number, number] },
  { id: 'riyadh', label: 'Riyad', coord: [46.6753, 24.7136] as [number, number] },
  { id: 'baghdad', label: 'Bagdat', coord: [44.3661, 33.3152] as [number, number] },
  { id: 'cairo', label: 'Kahire', coord: [31.2357, 30.0444] as [number, number] },
] as const

export const MISSILE_STRATEGIC_DISTANCES = [
  { id: 'tehran_tel_aviv', label: 'Tahran → Tel Aviv', distanceKm: 1576 },
  { id: 'isfahan_tel_aviv', label: 'Isfahan → Tel Aviv', distanceKm: 1603 },
  { id: 'tabriz_ankara', label: 'Tabriz → Ankara', distanceKm: 1180 },
  { id: 'palmachim_tehran', label: 'Palmachim → Tahran', distanceKm: 1580 },
] as const

export const MISSILE_CATEGORY_LABELS: Record<MissileDefinition['category'], string> = {
  srbm: 'SRBM',
  mrbm: 'MRBM',
  irbm: 'IRBM',
  icbm: 'ICBM',
  cruise: 'Cruise',
  hypersonic: 'Hipersonik',
  asbm: 'ASBM',
  tactical: 'Taktik',
  interceptor: 'Savunma',
  directed_energy: 'Lazer',
  slv: 'SLV',
}

const COUNTRY_THEME_DEFAULTS: Record<MissileCountry, { launchCoord: [number, number]; sites: MissileLaunchSite[] }> = {
  iran: {
    launchCoord: IRAN_DEFAULT_LAUNCH_COORD,
    sites: IRAN_LAUNCH_SITES,
  },
  israel: {
    launchCoord: ISRAEL_DEFAULT_LAUNCH_COORD,
    sites: ISRAEL_LAUNCH_SITES,
  },
}

function missile(input: MissileInput): MissileDefinition {
  const countryDefaults = COUNTRY_THEME_DEFAULTS[input.country]
  const {
    altNames = [],
    guidance = [],
    launchPlatform = [],
    warheadType = [],
    features = [],
    estimatedInventory = null,
    interceptProbability = null,
    defaultLaunchCoord = countryDefaults.launchCoord,
    knownLaunchSites = countryDefaults.sites,
    ...rest
  } = input

  return {
    ...rest,
    altNames,
    guidance,
    launchPlatform,
    warheadType,
    features,
    estimatedInventory,
    interceptProbability,
    defaultLaunchCoord,
    knownLaunchSites,
  }
}

const ISRAEL_DEFENSE_LAUNCH: [number, number] = [34.6905, 31.8977]

export const MISSILE_DEFINITIONS: MissileDefinition[] = [
  missile({
    id: 'iran_fateh_110',
    country: 'iran',
    name: 'Fateh-110',
    category: 'srbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 300,
    rangeMaxKm: 300,
    payloadKg: 450,
    cepMeters: 100,
    speed: 'supersonic',
    machNumber: 3,
    firstYear: 2002,
    status: 'operational',
    guidance: ['INS', 'terminal guidance'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
    features: ['solid-fuel SRBM'],
  }),
  missile({
    id: 'iran_fateh_313',
    country: 'iran',
    name: 'Fateh-313',
    category: 'srbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 500,
    rangeMaxKm: 500,
    payloadKg: 350,
    cepMeters: 20,
    speed: 'supersonic',
    machNumber: 4,
    firstYear: 2015,
    status: 'operational',
    guidance: ['INS', 'GNSS', 'terminal guidance'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
    features: ['extended-range Fateh variant'],
  }),
  missile({
    id: 'iran_raad_500',
    country: 'iran',
    name: 'Raad-500',
    category: 'srbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 500,
    rangeMaxKm: 500,
    payloadKg: null,
    cepMeters: 30,
    speed: 'supersonic',
    machNumber: 4,
    firstYear: 2020,
    status: 'testing',
    guidance: ['INS', 'terminal guidance'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
    features: ['composite motor casing'],
  }),
  missile({
    id: 'iran_shahab_1',
    country: 'iran',
    name: 'Shahab-1',
    altNames: ['Scud B'],
    category: 'srbm',
    type: 'ballistic',
    propulsion: 'liquid',
    stages: 1,
    rangeMinKm: 300,
    rangeMaxKm: 300,
    payloadKg: 885,
    cepMeters: 500,
    speed: 'supersonic',
    machNumber: 3,
    firstYear: 1988,
    status: 'retired',
    guidance: ['INS'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_shahab_2',
    country: 'iran',
    name: 'Shahab-2',
    altNames: ['Scud C'],
    category: 'srbm',
    type: 'ballistic',
    propulsion: 'liquid',
    stages: 1,
    rangeMinKm: 500,
    rangeMaxKm: 500,
    payloadKg: 700,
    cepMeters: 700,
    speed: 'supersonic',
    machNumber: 3,
    firstYear: 1994,
    status: 'operational',
    guidance: ['INS'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_qiam_1',
    country: 'iran',
    name: 'Qiam-1',
    category: 'srbm',
    type: 'ballistic',
    propulsion: 'liquid',
    stages: 1,
    rangeMinKm: 700,
    rangeMaxKm: 800,
    payloadKg: 650,
    cepMeters: 500,
    speed: 'supersonic',
    machNumber: 4,
    firstYear: 2010,
    status: 'operational',
    guidance: ['INS', 'terminal control'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
    features: ['finless design'],
  }),
  missile({
    id: 'iran_zolfaghar',
    country: 'iran',
    name: 'Zolfaghar',
    altNames: ['Zolfaghar Basir'],
    category: 'srbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 700,
    rangeMaxKm: 700,
    payloadKg: 525,
    cepMeters: 20,
    speed: 'supersonic',
    machNumber: 4,
    firstYear: 2016,
    status: 'operational',
    guidance: ['INS', 'electro-optical terminal guidance'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_dezful',
    country: 'iran',
    name: 'Dezful',
    category: 'srbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 1000,
    rangeMaxKm: 1000,
    payloadKg: 525,
    cepMeters: 20,
    speed: 'supersonic',
    machNumber: 4,
    firstYear: 2019,
    status: 'operational',
    guidance: ['INS', 'terminal guidance'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_shahab_3',
    country: 'iran',
    name: 'Shahab-3',
    category: 'mrbm',
    type: 'ballistic',
    propulsion: 'liquid',
    stages: 1,
    rangeMinKm: 1300,
    rangeMaxKm: 1300,
    payloadKg: 875,
    cepMeters: 3000,
    speed: 'supersonic',
    machNumber: 7,
    firstYear: 2003,
    status: 'operational',
    guidance: ['INS'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_ghadr',
    country: 'iran',
    name: 'Ghadr',
    category: 'mrbm',
    type: 'ballistic',
    propulsion: 'liquid',
    stages: 1,
    rangeMinKm: 1600,
    rangeMaxKm: 1600,
    payloadKg: 750,
    cepMeters: 300,
    speed: 'supersonic',
    machNumber: 8,
    firstYear: 2007,
    status: 'operational',
    guidance: ['INS', 'improved terminal guidance'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
    features: ['Shahab-3 derivative'],
  }),
  missile({
    id: 'iran_emad',
    country: 'iran',
    name: 'Emad',
    category: 'mrbm',
    type: 'ballistic',
    propulsion: 'liquid',
    stages: 1,
    rangeMinKm: 1800,
    rangeMaxKm: 1800,
    payloadKg: 750,
    cepMeters: 500,
    speed: 'supersonic',
    machNumber: 8,
    firstYear: 2015,
    status: 'operational',
    guidance: ['INS', 'maneuvering re-entry vehicle'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_qassem_basir',
    country: 'iran',
    name: 'Qassem Basir',
    category: 'mrbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 1200,
    rangeMaxKm: 1200,
    payloadKg: 500,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 6,
    firstYear: 2024,
    status: 'testing',
    guidance: ['INS', 'electro-optical terminal guidance'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_haj_qassem',
    country: 'iran',
    name: 'Haj Qassem',
    category: 'mrbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 1400,
    rangeMaxKm: 1400,
    payloadKg: 500,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 7,
    firstYear: 2020,
    status: 'operational',
    guidance: ['INS', 'terminal guidance'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_kheibar_shekan',
    country: 'iran',
    name: 'Kheibar Shekan',
    category: 'mrbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 1450,
    rangeMaxKm: 1450,
    payloadKg: 525,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 7,
    firstYear: 2022,
    status: 'operational',
    guidance: ['INS', 'maneuvering terminal guidance'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
    features: ['solid-fuel MRBM', 'not Khorramshahr-4'],
  }),
  missile({
    id: 'iran_etemad',
    country: 'iran',
    name: 'Etemad',
    category: 'mrbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 1700,
    rangeMaxKm: 1700,
    payloadKg: null,
    cepMeters: 70,
    speed: 'supersonic',
    machNumber: 7,
    firstYear: 2025,
    status: 'limited_operational',
    guidance: ['INS', 'terminal guidance'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_sejjil',
    country: 'iran',
    name: 'Sejjil',
    category: 'mrbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 2,
    rangeMinKm: 2000,
    rangeMaxKm: 2000,
    payloadKg: 750,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 10,
    firstYear: 2008,
    status: 'operational',
    guidance: ['INS'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
    features: ['two-stage solid-fuel MRBM'],
  }),
  missile({
    id: 'iran_khorramshahr',
    country: 'iran',
    name: 'Khorramshahr',
    altNames: ['Khorramshahr-1', 'Khorramshahr-2', 'Khorramshahr-4'],
    category: 'mrbm',
    type: 'ballistic',
    propulsion: 'liquid',
    stages: 1,
    rangeMinKm: 2000,
    rangeMaxKm: 3000,
    payloadKg: 1125,
    cepMeters: 30,
    speed: 'supersonic',
    machNumber: 8,
    firstYear: 2017,
    status: 'operational',
    guidance: ['INS', 'terminal guidance'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_fattah_1',
    country: 'iran',
    name: 'Fattah-1',
    category: 'hypersonic',
    type: 'hypersonic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 1400,
    rangeMaxKm: 1400,
    payloadKg: null,
    cepMeters: null,
    speed: 'hypersonic',
    machNumber: 15,
    firstYear: 2023,
    status: 'operational',
    guidance: ['maneuvering warhead'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
    features: ['claimed Mach 15'],
  }),
  missile({
    id: 'iran_fattah_2',
    country: 'iran',
    name: 'Fattah-2',
    category: 'hypersonic',
    type: 'hypersonic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 1500,
    rangeMaxKm: 1500,
    payloadKg: null,
    cepMeters: null,
    speed: 'hypersonic',
    machNumber: 15,
    firstYear: 2023,
    status: 'limited_operational',
    guidance: ['HGV glide vehicle'],
    launchPlatform: ['road-mobile TEL'],
    warheadType: ['HE'],
    features: ['claimed hypersonic glide vehicle'],
  }),
  missile({
    id: 'iran_ya_ali',
    country: 'iran',
    name: 'Ya Ali',
    category: 'cruise',
    type: 'cruise',
    propulsion: 'turbojet',
    stages: 1,
    rangeMinKm: 700,
    rangeMaxKm: 700,
    payloadKg: null,
    cepMeters: null,
    speed: 'subsonic',
    machNumber: 0.8,
    firstYear: 2014,
    status: 'testing',
    guidance: ['terrain reference', 'GPS/INS'],
    launchPlatform: ['ground launcher'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_hoveyzeh',
    country: 'iran',
    name: 'Hoveyzeh',
    category: 'cruise',
    type: 'cruise',
    propulsion: 'turbojet',
    stages: 1,
    rangeMinKm: 1350,
    rangeMaxKm: 1350,
    payloadKg: null,
    cepMeters: null,
    speed: 'subsonic',
    machNumber: 0.8,
    firstYear: 2019,
    status: 'operational',
    guidance: ['terrain following', 'GPS/INS'],
    launchPlatform: ['ground launcher'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_paveh',
    country: 'iran',
    name: 'Paveh',
    altNames: ['Quds', '351'],
    category: 'cruise',
    type: 'cruise',
    propulsion: 'turbojet',
    stages: 1,
    rangeMinKm: 1650,
    rangeMaxKm: 1650,
    payloadKg: null,
    cepMeters: null,
    speed: 'subsonic',
    machNumber: 0.8,
    firstYear: 2023,
    status: 'operational',
    guidance: ['terrain following', 'GPS/INS'],
    launchPlatform: ['ground launcher'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'iran_soumar',
    country: 'iran',
    name: 'Soumar',
    altNames: ['Kh-55 derivative'],
    category: 'cruise',
    type: 'cruise',
    propulsion: 'turbojet',
    stages: 1,
    rangeMinKm: null,
    rangeMaxKm: 3000,
    payloadKg: null,
    cepMeters: null,
    speed: 'subsonic',
    machNumber: 0.8,
    firstYear: 2015,
    status: 'operational',
    guidance: ['terrain following', 'GPS/INS'],
    launchPlatform: ['ground launcher'],
    warheadType: ['HE'],
    features: ['estimated 2000-3000 km'],
  }),
  missile({
    id: 'iran_khalij_fars',
    country: 'iran',
    name: 'Khalij Fars',
    category: 'asbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 300,
    rangeMaxKm: 300,
    payloadKg: null,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 4,
    firstYear: 2011,
    status: 'operational',
    guidance: ['anti-ship terminal seeker'],
    launchPlatform: ['coastal launcher'],
    warheadType: ['anti-ship'],
  }),
  missile({
    id: 'iran_hormuz',
    country: 'iran',
    name: 'Hormuz-1/2',
    category: 'asbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 300,
    rangeMaxKm: 300,
    payloadKg: null,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 4,
    firstYear: 2014,
    status: 'operational',
    guidance: ['anti-radiation seeker'],
    launchPlatform: ['coastal launcher'],
    warheadType: ['anti-ship', 'anti-radiation'],
  }),
  missile({
    id: 'iran_ghadr_380',
    country: 'iran',
    name: 'Ghadr-380',
    category: 'asbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 1000,
    rangeMaxKm: 1000,
    payloadKg: null,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 5,
    firstYear: 2024,
    status: 'testing',
    guidance: ['anti-ship terminal seeker'],
    launchPlatform: ['coastal launcher'],
    warheadType: ['anti-ship'],
  }),
  missile({
    id: 'iran_safir',
    country: 'iran',
    name: 'Safir',
    category: 'slv',
    type: 'slv_dual_use',
    propulsion: 'liquid',
    stages: 2,
    rangeMinKm: 2100,
    rangeMaxKm: 2100,
    payloadKg: 625,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 12,
    firstYear: 2008,
    status: 'retired',
    guidance: ['orbital launch guidance'],
    launchPlatform: ['fixed pad'],
    warheadType: [],
    features: ['dual-use SLV'],
  }),
  missile({
    id: 'iran_simorgh',
    country: 'iran',
    name: 'Simorgh',
    category: 'slv',
    type: 'slv_dual_use',
    propulsion: 'liquid',
    stages: 2,
    rangeMinKm: 4000,
    rangeMaxKm: 6000,
    payloadKg: 625,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 15,
    firstYear: 2016,
    status: 'operational',
    guidance: ['orbital launch guidance'],
    launchPlatform: ['fixed pad'],
    warheadType: [],
    features: ['space launch vehicle'],
  }),
  missile({
    id: 'iran_qased',
    country: 'iran',
    name: 'Qased',
    category: 'slv',
    type: 'slv_dual_use',
    propulsion: 'hybrid',
    stages: 3,
    rangeMinKm: 2200,
    rangeMaxKm: 2200,
    payloadKg: 1000,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 15,
    firstYear: 2020,
    status: 'operational',
    guidance: ['orbital launch guidance'],
    launchPlatform: ['fixed pad'],
    warheadType: [],
    features: ['IRGC space launcher'],
  }),
  missile({
    id: 'iran_zoljanah',
    country: 'iran',
    name: 'Zoljanah',
    category: 'slv',
    type: 'slv_dual_use',
    propulsion: 'hybrid',
    stages: 3,
    rangeMinKm: 4000,
    rangeMaxKm: 5000,
    payloadKg: 1000,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 16,
    firstYear: 2021,
    status: 'testing',
    guidance: ['orbital launch guidance'],
    launchPlatform: ['fixed pad'],
    warheadType: [],
    features: ['solid + liquid staging'],
  }),
  missile({
    id: 'iran_ghaem_100',
    country: 'iran',
    name: 'Ghaem-100',
    category: 'slv',
    type: 'slv_dual_use',
    propulsion: 'solid',
    stages: 3,
    rangeMinKm: 3000,
    rangeMaxKm: 4000,
    payloadKg: 1000,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 16,
    firstYear: 2022,
    status: 'operational',
    guidance: ['orbital launch guidance'],
    launchPlatform: ['fixed pad'],
    warheadType: [],
    features: ['solid-fuel SLV'],
  }),
  missile({
    id: 'israel_jericho_1',
    country: 'israel',
    name: 'Jericho I',
    category: 'srbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 500,
    rangeMaxKm: 720,
    payloadKg: 650,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 4,
    firstYear: 1971,
    status: 'retired',
    guidance: ['INS'],
    launchPlatform: ['fixed silo', 'TEL'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'israel_jericho_2',
    country: 'israel',
    name: 'Jericho II',
    category: 'mrbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 2,
    rangeMinKm: 1500,
    rangeMaxKm: 3500,
    payloadKg: 1000,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 8,
    firstYear: 1989,
    status: 'operational',
    guidance: ['INS'],
    launchPlatform: ['fixed silo', 'TEL'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'israel_jericho_3',
    country: 'israel',
    name: 'Jericho III',
    category: 'irbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 2,
    rangeMinKm: 4800,
    rangeMaxKm: 11500,
    payloadKg: 1150,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 15,
    firstYear: 2011,
    status: 'operational',
    guidance: ['INS'],
    launchPlatform: ['fixed silo', 'TEL'],
    warheadType: ['HE'],
    features: ['range varies with payload'],
  }),
  missile({
    id: 'israel_jericho_4',
    country: 'israel',
    name: 'Jericho IV',
    category: 'irbm',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 2,
    rangeMinKm: null,
    rangeMaxKm: null,
    payloadKg: null,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: null,
    firstYear: 2025,
    status: 'in_development',
    guidance: ['INS'],
    launchPlatform: ['fixed silo'],
    warheadType: [],
  }),
  missile({
    id: 'israel_lora',
    country: 'israel',
    name: 'LORA',
    category: 'tactical',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 280,
    rangeMaxKm: 400,
    payloadKg: 600,
    cepMeters: 10,
    speed: 'supersonic',
    machNumber: 5,
    firstYear: 2017,
    status: 'operational',
    guidance: ['INS', 'GPS'],
    launchPlatform: ['road launcher', 'naval launcher'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'israel_rampage',
    country: 'israel',
    name: 'Rampage',
    category: 'tactical',
    type: 'ballistic',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 150,
    rangeMaxKm: 250,
    payloadKg: 150,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 3,
    firstYear: 2018,
    status: 'operational',
    guidance: ['INS', 'GPS'],
    launchPlatform: ['air launch'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'israel_popeye',
    country: 'israel',
    name: 'Popeye',
    altNames: ['AGM-142'],
    category: 'cruise',
    type: 'cruise',
    propulsion: 'turbojet',
    stages: 1,
    rangeMinKm: 80,
    rangeMaxKm: 90,
    payloadKg: null,
    cepMeters: null,
    speed: 'subsonic',
    machNumber: 0.8,
    firstYear: 1985,
    status: 'operational',
    guidance: ['TV/IIR', 'data link'],
    launchPlatform: ['air launch'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'israel_delilah',
    country: 'israel',
    name: 'Delilah',
    category: 'cruise',
    type: 'cruise',
    propulsion: 'turbojet',
    stages: 1,
    rangeMinKm: 250,
    rangeMaxKm: 300,
    payloadKg: null,
    cepMeters: null,
    speed: 'subsonic',
    machNumber: 0.7,
    firstYear: 2003,
    status: 'operational',
    guidance: ['loitering seeker', 'data link'],
    launchPlatform: ['air launch'],
    warheadType: ['HE'],
  }),
  missile({
    id: 'israel_popeye_slcm',
    country: 'israel',
    name: 'Popeye Turbo SLCM',
    category: 'cruise',
    type: 'cruise',
    propulsion: 'turbojet',
    stages: 1,
    rangeMinKm: 1500,
    rangeMaxKm: 1500,
    payloadKg: null,
    cepMeters: null,
    speed: 'subsonic',
    machNumber: 0.8,
    firstYear: 2002,
    status: 'operational',
    guidance: ['GPS/INS', 'terrain following'],
    launchPlatform: ['submarine launch'],
    warheadType: ['HE'],
    features: ['second-strike SLCM'],
  }),
  missile({
    id: 'israel_gabriel_v',
    country: 'israel',
    name: 'Gabriel V',
    category: 'tactical',
    type: 'cruise',
    propulsion: 'turbojet',
    stages: 1,
    rangeMinKm: 200,
    rangeMaxKm: 400,
    payloadKg: null,
    cepMeters: null,
    speed: 'subsonic',
    machNumber: 0.8,
    firstYear: 2020,
    status: 'operational',
    guidance: ['anti-ship seeker'],
    launchPlatform: ['naval launch'],
    warheadType: ['anti-ship'],
  }),
  missile({
    id: 'israel_spike_nlos',
    country: 'israel',
    name: 'Spike NLOS',
    category: 'tactical',
    type: 'cruise',
    propulsion: 'turbojet',
    stages: 1,
    rangeMinKm: 32,
    rangeMaxKm: 32,
    payloadKg: null,
    cepMeters: null,
    speed: 'subsonic',
    machNumber: 0.7,
    firstYear: 2009,
    status: 'operational',
    guidance: ['electro-optical', 'data link'],
    launchPlatform: ['ground launch', 'air launch'],
    warheadType: ['HEAT', 'HE'],
  }),
  missile({
    id: 'israel_shavit',
    country: 'israel',
    name: 'Shavit',
    category: 'slv',
    type: 'slv_dual_use',
    propulsion: 'solid',
    stages: 3,
    rangeMinKm: 5300,
    rangeMaxKm: 7800,
    payloadKg: null,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 15,
    firstYear: 1988,
    status: 'operational',
    guidance: ['orbital launch guidance'],
    launchPlatform: ['fixed pad'],
    warheadType: [],
    defaultLaunchCoord: [34.6905, 31.8977],
    features: ['dual-use SLV'],
  }),
  missile({
    id: 'israel_iron_dome',
    country: 'israel',
    name: 'Iron Dome',
    category: 'interceptor',
    type: 'interceptor',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 4,
    rangeMaxKm: 70,
    payloadKg: null,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 2,
    firstYear: 2011,
    status: 'operational',
    guidance: ['radar command guidance'],
    launchPlatform: ['ground battery'],
    warheadType: ['interceptor'],
    defaultLaunchCoord: ISRAEL_DEFENSE_LAUNCH,
    features: ['terminal SHORAD'],
    interceptProbability: 0.85,
  }),
  missile({
    id: 'israel_iron_beam',
    country: 'israel',
    name: 'Iron Beam',
    category: 'directed_energy',
    type: 'directed_energy',
    propulsion: 'laser',
    stages: 1,
    rangeMinKm: 0,
    rangeMaxKm: 10,
    payloadKg: null,
    cepMeters: null,
    speed: 'hypersonic',
    machNumber: null,
    firstYear: 2025,
    status: 'operational',
    guidance: ['beam steering'],
    launchPlatform: ['ground battery'],
    warheadType: ['laser'],
    defaultLaunchCoord: ISRAEL_DEFENSE_LAUNCH,
    features: ['high-energy laser'],
    interceptProbability: 0.8,
  }),
  missile({
    id: 'israel_davids_sling',
    country: 'israel',
    name: "David's Sling",
    category: 'interceptor',
    type: 'interceptor',
    propulsion: 'solid',
    stages: 2,
    rangeMinKm: 40,
    rangeMaxKm: 300,
    payloadKg: null,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 4,
    firstYear: 2017,
    status: 'operational',
    guidance: ['active radar seeker'],
    launchPlatform: ['ground battery'],
    warheadType: ['interceptor'],
    defaultLaunchCoord: ISRAEL_DEFENSE_LAUNCH,
    interceptProbability: 0.85,
  }),
  missile({
    id: 'israel_barak_8',
    country: 'israel',
    name: 'Barak 8',
    category: 'interceptor',
    type: 'interceptor',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 0,
    rangeMaxKm: 70,
    payloadKg: null,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 3,
    firstYear: 2015,
    status: 'operational',
    guidance: ['active radar seeker'],
    launchPlatform: ['ship', 'ground battery'],
    warheadType: ['interceptor'],
    defaultLaunchCoord: ISRAEL_DEFENSE_LAUNCH,
    interceptProbability: 0.78,
  }),
  missile({
    id: 'israel_barak_er',
    country: 'israel',
    name: 'Barak ER',
    category: 'interceptor',
    type: 'interceptor',
    propulsion: 'solid',
    stages: 1,
    rangeMinKm: 0,
    rangeMaxKm: 150,
    payloadKg: null,
    cepMeters: null,
    speed: 'supersonic',
    machNumber: 4,
    firstYear: 2022,
    status: 'operational',
    guidance: ['active radar seeker'],
    launchPlatform: ['ship', 'ground battery'],
    warheadType: ['interceptor'],
    defaultLaunchCoord: ISRAEL_DEFENSE_LAUNCH,
    interceptProbability: 0.78,
  }),
  missile({
    id: 'israel_arrow_2',
    country: 'israel',
    name: 'Arrow 2',
    category: 'interceptor',
    type: 'interceptor',
    propulsion: 'solid',
    stages: 2,
    rangeMinKm: 0,
    rangeMaxKm: 100,
    payloadKg: null,
    cepMeters: null,
    speed: 'hypersonic',
    machNumber: 9,
    firstYear: 2000,
    status: 'operational',
    guidance: ['exo/endo-atmospheric intercept guidance'],
    launchPlatform: ['ground battery'],
    warheadType: ['interceptor'],
    defaultLaunchCoord: ISRAEL_DEFENSE_LAUNCH,
    interceptProbability: 0.82,
  }),
  missile({
    id: 'israel_arrow_3',
    country: 'israel',
    name: 'Arrow 3',
    category: 'interceptor',
    type: 'interceptor',
    propulsion: 'solid',
    stages: 2,
    rangeMinKm: 0,
    rangeMaxKm: 2400,
    payloadKg: null,
    cepMeters: null,
    speed: 'hypersonic',
    machNumber: 10,
    firstYear: 2017,
    status: 'operational',
    guidance: ['exo-atmospheric hit-to-kill'],
    launchPlatform: ['ground battery'],
    warheadType: ['interceptor'],
    defaultLaunchCoord: ISRAEL_DEFENSE_LAUNCH,
    interceptProbability: 0.9,
  }),
  missile({
    id: 'israel_arrow_4',
    country: 'israel',
    name: 'Arrow 4',
    category: 'interceptor',
    type: 'interceptor',
    propulsion: 'solid',
    stages: 2,
    rangeMinKm: 0,
    rangeMaxKm: 200,
    payloadKg: null,
    cepMeters: null,
    speed: 'hypersonic',
    machNumber: 9,
    firstYear: 2024,
    status: 'testing',
    guidance: ['anti-HGV intercept guidance'],
    launchPlatform: ['ground battery'],
    warheadType: ['interceptor'],
    defaultLaunchCoord: ISRAEL_DEFENSE_LAUNCH,
    interceptProbability: 0.75,
  }),
]

export const MISSILE_DEFINITIONS_BY_ID = new Map(
  MISSILE_DEFINITIONS.map((definition) => [definition.id, definition]),
)

export function getMissileById(id: string) {
  return MISSILE_DEFINITIONS_BY_ID.get(id) ?? null
}

export function getMissilesByCountry(country: MissileCountry) {
  return MISSILE_DEFINITIONS.filter((definition) => definition.country === country)
}
